from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from backend.app.utils.logger import logger
from backend.app.services.rag_service import generate_answer

router = APIRouter()


class QuestionRequest(BaseModel):
    question: str = Field(
        ...,
        description="Question asked by the user",
        example="What is OmniBrain?",
    )

    document_id: str = Field(
        ...,
        description="ID of the uploaded document",
    )


@router.post(
    "/ask",
    summary="Ask Question",
    description="Receives a user question and returns an answer generated by the RAG service.",
    responses={
        200: {"description": "Answer generated successfully"},
        400: {"description": "Invalid question"},
        500: {"description": "Internal Server Error"},
    },
)
async def ask_question(request: QuestionRequest):
    try:
        if not request.question.strip():
            raise HTTPException(
                status_code=400,
                detail="Question cannot be empty.",
            )

        logger.info(f"Question received: {request.question}")

        answer = await generate_answer(
            request.question,
            request.document_id,
        )

        return {
            "question": request.question,
            "answer": answer["answer"],
            "sources": answer["sources"],
        }

    except HTTPException:
        raise

    except Exception:
        logger.exception("Ask API failed")
        raise HTTPException(
            status_code=500,
            detail="Internal Server Error",
        )
