from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from app.utils.logger import logger
from app.services.rag_service import generate_answer

router = APIRouter()


class QuestionRequest(BaseModel):
    question: str = Field(
        ..., description="Question asked by the user", example="What is OmniBrain?"
    )


@router.post(
    "/ask",
    summary="Ask Question",
    description="Receives a user question and returns an answer generated by the RAG service.",
    responses={
        200: {"description": "Answer generated successfully"},
        400: {"description": "Invalid question"},
        500: {"description": "Internal Server Error"},
    },
)
async def ask_question(request: QuestionRequest):
    try:

        # Validate question
        if not request.question.strip():
            raise HTTPException(status_code=400, detail="Question cannot be empty.")

        # Log incoming request
        logger.info(f"Question received: {request.question}")

        # Generate answer using RAG service
        result = await generate_answer(request.question)

        # Return response
        return {
            "question": request.question,
            "answer": result["answer"],
            "sources": result["sources"],
        }

    except HTTPException:
        raise

    except Exception as e:
        logger.error(f"Ask API failed: {str(e)}")

        raise HTTPException(
            status_code=500,
            detail="Internal Server Error",
        )

        
